wget neuralnetworksanddeeplearning.com/images/mnist_100_digits.png 
wget neuralnetworksanddeeplearning.com/images/tikz0.png 
wget neuralnetworksanddeeplearning.com/images/tikz1.png 
wget neuralnetworksanddeeplearning.com/images/tikz8.png 
wget lh3.googleusercontent.com/-WNMDpgwcC7I/VYk-QEgs9DI/AAAAAAAAAT8/MKuAMcVDYcM/s0/sigmoid_function.png 
wget lh3.googleusercontent.com/-lIMAxDaKs5U/VYlCQHeg_1I/AAAAAAAAAUM/gQwIY5OWpAo/s0/step_function.png 
wget neuralnetworksanddeeplearning.com/images/tikz10.png 
wget neuralnetworksanddeeplearning.com/images/tikz11.png 
wget neuralnetworksanddeeplearning.com/images/digits_separate.png 
wget neuralnetworksanddeeplearning.com/images/tikz12.png 
wget neuralnetworksanddeeplearning.com/images/mnist_other_features.png 
wget neuralnetworksanddeeplearning.com/images/digits_separate.png
wget neuralnetworksanddeeplearning.com/images/valley.png 
wget neuralnetworksanddeeplearning.com/images/tikz16.png 
wget neuralnetworksanddeeplearning.com/images/tikz17.png 
wget neuralnetworksanddeeplearning.com/images/tikz18.png 
wget neuralnetworksanddeeplearning.com/images/tikz21.png 
wget neuralnetworksanddeeplearning.com/images/tikz22.png 
wget neuralnetworksanddeeplearning.com/images/tikz23.png 
wget neuralnetworksanddeeplearning.com/images/tikz24.png 
wget neuralnetworksanddeeplearning.com/images/tikz25.png 
wget neuralnetworksanddeeplearning.com/images/tikz26.png 
wget neuralnetworksanddeeplearning.com/images/tikz27.png 
wget neuralnetworksanddeeplearning.com/images/tikz28.png 
wget lh3.googleusercontent.com/-XMhTxcBFyJc/VZULqrdycxI/AAAAAAAAAU4/tRj1DIVkbTQ/s0/single_neuron\%2528w\%253D0.6\%252Cb\%253D0.9\%2529.png 
wget lh3.googleusercontent.com/-yWskvCDvRP8/VZULicYhmpI/AAAAAAAAAUs/LN7yVyhkN4Q/s0/single_neuron\%2528w\%253D2.0\%252Cb\%253D2.0\%2529.png 
wget neuralnetworksanddeeplearning.com/images/tikz29.png 
wget lh3.googleusercontent.com/-xP058zOE2KI/VZaBS3nLgfI/AAAAAAAAAVY/OcJVL7bxpMg/s0/single_neuron\%2528w\%253D0.6\%252Cb\%253D0.9\%wget2529_cross_entropy_cost.png 
wget lh3.googleusercontent.com/-a-04S0ASN1g/VZaBbz1zOUI/AAAAAAAAAVk/cVsHwrnmW6A/s0/single_neuron\%2528w\%253D2.0\%252Cb\%253D2.0\%2529_cross_entropy_cost.png 
wget neuralnetworksanddeeplearning.com/images/overfitting1.png 
wget neuralnetworksanddeeplearning.com/images/overfitting2.png 
wget neuralnetworksanddeeplearning.com/images/overfitting4.png 
wget neuralnetworksanddeeplearning.com/images/overfitting_full.png 
wget neuralnetworksanddeeplearning.com/images/regularized1.png  
wget neuralnetworksanddeeplearning.com/images/regularized2.png 
wget neuralnetworksanddeeplearning.com/images/regularized_full.png 
wget neuralnetworksanddeeplearning.com/images/tikz30.png 
wget neuralnetworksanddeeplearning.com/images/tikz31.png 
wget neuralnetworksanddeeplearning.com/images/more_data_5.png 
wget neuralnetworksanddeeplearning.com/images/more_data_rotated_5.png 
wget neuralnetworksanddeeplearning.com/images/more_data_log.png 
wget neuralnetworksanddeeplearning.com/images/more_data_comparison.png 
wget lh3.googleusercontent.com/-dyDRsew7UAE/VaVznnqH36I/AAAAAAAAAWc/yC865e0mAwM/s0/gaussian_mean0_variance22.4.png 
wget lh3.googleusercontent.com/-O7BhA-gnnVo/VaV1r2ynk4I/AAAAAAAAAWs/VMpO3W7EGEk/s0/gaussian_mean0_variance1.22.png 
wget neuralnetworksanddeeplearning.com/images/weight_initialization_30.png 
wget neuralnetworksanddeeplearning.com/images/multiple_eta.png 
wget lh3.googleusercontent.com/-WdNc0bJLb2I/VaWzLYtYaQI/AAAAAAAAAXE/U_PDsxTK3-c/s0/tanh_function.png 
wget lh3.googleusercontent.com/-4GxP-qqhtBo/VaW3--JDLZI/AAAAAAAAAXU/EgWAXlQqNEw/s0/rectifying_function.png 
